// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBRht7EwecJmeiaAM8M1D2GW5Z0_oKzaiI',
    appId: '1:748283418756:web:3677100888133565d64ad1',
    messagingSenderId: '748283418756',
    projectId: 'parksnap-74d9e',
    authDomain: 'parksnap-74d9e.firebaseapp.com',
    storageBucket: 'parksnap-74d9e.firebasestorage.app',
    measurementId: 'G-JL128X3BTD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBp12fCqEg9oCsLocLevPI4HNFKflkX-A0',
    appId: '1:748283418756:android:a41926ae126f9c62d64ad1',
    messagingSenderId: '748283418756',
    projectId: 'parksnap-74d9e',
    storageBucket: 'parksnap-74d9e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDWNmbj3V_41MNnSEjHdzQxmdYvgolIcpM',
    appId: '1:748283418756:ios:29d0424f2e6e96c3d64ad1',
    messagingSenderId: '748283418756',
    projectId: 'parksnap-74d9e',
    storageBucket: 'parksnap-74d9e.firebasestorage.app',
    iosBundleId: 'com.parksnap.parkSnap',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDWNmbj3V_41MNnSEjHdzQxmdYvgolIcpM',
    appId: '1:748283418756:ios:29d0424f2e6e96c3d64ad1',
    messagingSenderId: '748283418756',
    projectId: 'parksnap-74d9e',
    storageBucket: 'parksnap-74d9e.firebasestorage.app',
    iosBundleId: 'com.parksnap.parkSnap',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBRht7EwecJmeiaAM8M1D2GW5Z0_oKzaiI',
    appId: '1:748283418756:web:c6a3dd4f53806d5dd64ad1',
    messagingSenderId: '748283418756',
    projectId: 'parksnap-74d9e',
    authDomain: 'parksnap-74d9e.firebaseapp.com',
    storageBucket: 'parksnap-74d9e.firebasestorage.app',
    measurementId: 'G-T3Q2730YXE',
  );
}
